export const NEXT_IMAGE = 'NEXT_IMAGE';
export const PREVIOUS_IMAGE = 'PREVIOUS_IMAGE';
export const CHANGE_IMAGE = 'CHANGE_IMAGE';
export const SET_IMAGE_DATA ='SET_IMAGE_DATA';
export const SET_IMAGES_FAILED='SET_IMAGES_FAILED';
